import 'dart:convert';

import 'package:flutter/foundation.dart';

import '../../../core/audio/audio_effects.dart';

/// A user-saved equalizer curve.
///
/// Levels are always stored normalized to [eqVirtualBandCount] entries. The id
/// is generated by the controller and is stable across renames so a selection
/// survives editing.
@immutable
class EqCustomPreset {
  const EqCustomPreset({
    required this.id,
    required this.name,
    required this.levels,
    this.pinned = false,
  });

  final String id;
  final String name;
  final List<double> levels;
  final bool pinned;

  EqCustomPreset copyWith({String? name, List<double>? levels, bool? pinned}) {
    return EqCustomPreset(
      id: id,
      name: name ?? this.name,
      levels: levels == null ? this.levels : normalizeEqLevels(levels),
      pinned: pinned ?? this.pinned,
    );
  }

  Map<String, Object?> toJson() => {
    'id': id,
    'name': name,
    'levels': levels,
    'pinned': pinned,
  };

  static EqCustomPreset? tryFromJson(Object? json) {
    if (json is! Map) return null;
    final id = json['id'];
    final name = json['name'];
    if (id is! String || id.isEmpty) return null;
    if (name is! String || name.isEmpty) return null;
    final rawLevels = json['levels'];
    final levels = rawLevels is List
        ? normalizeEqLevels([
            for (final value in rawLevels)
              if (value is num) value.toDouble() else 0.0,
          ])
        : normalizeEqLevels(const []);
    return EqCustomPreset(
      id: id,
      name: name,
      levels: levels,
      pinned: json['pinned'] == true,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqCustomPreset &&
          other.id == id &&
          other.name == name &&
          other.pinned == pinned &&
          listEquals(other.levels, levels);

  @override
  int get hashCode => Object.hash(id, name, pinned, Object.hashAll(levels));
}

/// Persisted equalizer UI preferences.
///
/// Kept separate from [AudioSettings] on purpose: the sound itself is still
/// described entirely by the audio pipeline settings, while this holds how the
/// user organizes and drives that one curve (mode, saved curves, selection).
@immutable
class EqualizerUiSettings {
  const EqualizerUiSettings({
    this.mode = EqMode.simple,
    this.presets = const [],
    this.selectedPresetId,
  });

  final EqMode mode;
  final List<EqCustomPreset> presets;

  /// Id of the saved preset currently selected, or null when a built-in preset
  /// or a free-edited curve is active.
  final String? selectedPresetId;

  EqCustomPreset? presetById(String? id) {
    if (id == null) return null;
    for (final preset in presets) {
      if (preset.id == id) return preset;
    }
    return null;
  }

  EqualizerUiSettings copyWith({
    EqMode? mode,
    List<EqCustomPreset>? presets,
    String? selectedPresetId,
    bool clearSelectedPreset = false,
  }) {
    return EqualizerUiSettings(
      mode: mode ?? this.mode,
      presets: presets ?? this.presets,
      selectedPresetId: clearSelectedPreset
          ? null
          : (selectedPresetId ?? this.selectedPresetId),
    );
  }

  String encode() => jsonEncode({
    'v': 1,
    'mode': mode.name,
    'selected': selectedPresetId,
    'presets': [for (final preset in presets) preset.toJson()],
  });

  /// Never throws: a corrupt blob resolves to the neutral default.
  static EqualizerUiSettings tryDecode(String source) {
    try {
      final decoded = jsonDecode(source);
      if (decoded is! Map) return const EqualizerUiSettings();
      final mode = EqMode.values.firstWhere(
        (m) => m.name == decoded['mode'],
        orElse: () => EqMode.simple,
      );
      final rawPresets = decoded['presets'];
      final presets = <EqCustomPreset>[];
      final seen = <String>{};
      if (rawPresets is List) {
        for (final raw in rawPresets) {
          final preset = EqCustomPreset.tryFromJson(raw);
          if (preset != null && seen.add(preset.id)) presets.add(preset);
        }
      }
      final selected = decoded['selected'];
      return EqualizerUiSettings(
        mode: mode,
        presets: presets,
        selectedPresetId: selected is String && seen.contains(selected)
            ? selected
            : null,
      );
    } catch (_) {
      return const EqualizerUiSettings();
    }
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqualizerUiSettings &&
          other.mode == mode &&
          other.selectedPresetId == selectedPresetId &&
          listEquals(other.presets, presets);

  @override
  int get hashCode =>
      Object.hash(mode, selectedPresetId, Object.hashAll(presets));
}
